#!/usr/bin/env bash

ORIDIR=$HOME/Documents/TeX_Notes/setup-nvim
DESTDIR1=$HOME/.vim/templates
DESTDIR2=$HOME/dotfiles/dotfiles/vim/templates

ln -sf $ORIDIR/tex-* $DESTDIR1/
ln -sf $ORIDIR/tex-* $DESTDIR2/
