#!/usr/bin/env dash

ORIDIR=$HOME/Documents/TeX_notes/setup-nvim
DESTDIR1=$HOME/.vim/templates
DESTDIR2=$HOME/dotfiles/dotfiles/vim/templates

cp $ORIDIR/tex_default.sh $DESTDIR1/
cp $ORIDIR/tex_default.sh $DESTDIR2/
