# This file is a template, and might need editing before it works on your project.
# Template project: https://gitlab.com/pages/jekyll
# Docs: https://docs.gitlab.com/ce/pages/
image: ruby:2.6

variables:
  JEKYLL_ENV: production

before_script:
  - ruby -v # Print version for debugging purposes
  - gem install bundler
  - bundle install -j $(nproc) --path vendor

test:
  stage: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - vendor/ruby
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - vendor/ruby
  script:
  - JEKYLL_ENV=production bundle exec jekyll build -I -d public
  artifacts:
    paths:
    - public
  only:
  - master

