image: ruby:2.7

variables:
  JEKYLL_ENV: production

before_script:
  - ruby -v # Print version for debugging purposes
  - gem install bundler
  - bundle config set path 'vendor'
  - bundle install -j $(nproc)

test:
  stage: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor/ruby
  script:
    - bundle exec jekyll build -d test --trace
  artifacts:
    paths:
      - test
  except:
  - master

pages:
  stage: deploy
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor/ruby
  script:
    - JEKYLL_ENV=production bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - master
