#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." >/dev/null 2>&1 && pwd )"
workingdir=""
filename="classnotes"
clean_flag=false
viewer_flag=true
lightdark="both"

viewer="$HOME/.bin/tabbed-zathura -i tvim-view -f"

usage() {
  echo "  Desc: watcher to build dark version of notes
  Options:
  -h    Show this help
  -d    Directory name [required]
  -c    Clean directory
  -l    build light/dark/both (default: both) (options: light, dark, both)
  -V    No viewer
  -f    Filename (default: classnotes)"
}

viewfile() {
  if ($viewer_flag); then
    case "${lightdark}" in
      "both" | "light") ${viewer} ${filename}.pdf ;;
      "dark") ${viewer} ${filename}-dark.pdf ;;
    esac
  fi
}

buildboth() {
  ls *.tex *.bib | entr -s "latexmk"
}

buildlight() {
  latexmk -pvc ${filename}.tex
}

builddark() {
  latexmk -pvc ${filename}-dark.tex
}

while getopts "hd:f:b:vcl:" flag; do
  case "${flag}" in
    h) usage ; exit 0 ;;
    d) workingdir=$DIR/$OPTARG ;;
    f) filename=$OPTARG ;;
    c) clean_flag=true ;;
    l) lightdark=$OPTARG ;;
    v) viewer_flag=false ;;
    *) usage ; exit 1 ;;
  esac
done

if [ "$workingdir" = "" ]; then
  echo "[builddark] Please provide directory name"
  exit 1
fi

workingdir=`eval "cd $workingdir;pwd;cd - > /dev/null"`

# working directory exists?
# true ->
#   want to clean?
#   false ->
#     build both?
#       true -> build both
#       false -> case lightdark
#   true -> clean working directory
# false -> report having no working directory
if [ -d $workingdir ]; then
  cd $workingdir

  if [ ! -f latexmkrc ]; then
    echo "[build] Warning! latexmkrc not found. You may want to create one."
  fi

  if ! $clean_flag ; then
    echo "[build] Hit Ctrl-c to kill"
    viewfile
    case "${lightdark}" in
      "both") buildboth ;;
      "light") buildlight ;;
      "dark") builddark ;;
    esac
  else
    latexmk -c
  fi
else
  echo "[build] Directory DNE! Terminating..."
  exit 1
fi
