#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." >/dev/null 2>&1 && pwd )"
workingdir=""
filename="classnotes"
clean_flag=false
viewer_flag=true

viewer="$HOME/.bin/tabbed-zathura -i tvim-view -f"

usage() {
  echo "  Desc: watcher to build dark version of notes
  Options:
  -h    Show this help
  -d    Directory name [required]
  -c    Clean directory
  -V    No viewer
  -f    Filename (default: classnotes)"
}

while getopts "hd:f:b:vc" flag; do
  case "${flag}" in
    h) usage ; exit 0 ;;
    d) workingdir=$DIR/$OPTARG ;;
    f) filename=$OPTARG ;;
    c) clean_flag=true ;;
    v) viewer_flag=false ;;
    *) usage ; exit 1 ;;
  esac
done

if [ "$workingdir" = "" ]; then
  echo "[builddark] Please provide directory name"
  exit 1
fi

workingdir=`eval "cd $workingdir;pwd;cd - > /dev/null"`

if [ -d $workingdir ]; then
  cd $workingdir

  if [ ! -f latexmkrc ]; then
    echo "[build] Warning! latexmkrc not found. You may want to create one."
  fi

  if ! $clean_flag ; then
    echo "[build] Hit Ctrl-c to kill"

    if ($viewer_flag); then
      ${viewer} ${filename}.pdf
    fi

    ls *.tex *.bib | entr -s "latexmk"
  else
    latexmk -c
  fi
else
  echo "[build] Directory DNE! Terminating..."
  exit 1
fi
